# Generated by Django 5.2.10 on 2026-01-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image_normal', models.ImageField(upload_to='artifacts/normal/', verbose_name='Обычное фото')),
                ('image_dark', models.ImageField(upload_to='artifacts/dark/', verbose_name='Жуткое фото')),
                ('description_normal', models.TextField(verbose_name='Обычное описание')),
                ('description_dark', models.TextField(verbose_name='Истинная суть')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
